// <auto-generated />
using APIController.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace APIController.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210802125411_seeding")]
    partial class seeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("APIController.Models.EmployeeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "mohad@harbi.com",
                            FirstName = "Mohammed",
                            LastName = "Alharbi"
                        },
                        new
                        {
                            Id = 3,
                            Email = "smth@gmail.com",
                            FirstName = "Ghada",
                            LastName = "Aldahalwi"
                        },
                        new
                        {
                            Id = 4,
                            Email = "Sami@gmail.com",
                            FirstName = "Sami",
                            LastName = "Aldahalwi"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
